### ISSUE TITLE
not responsive table

### ISSUE THREAD

**Issue by papiyot** [Seungwoo321/vue-pivottable#18]

**Comment by lalo4ka** [comment]
same here.  

problem with getting 100% parent div width.

![image](https://user-images.githubusercontent.com/1745823/81480698-df22cd80-91f0-11ea-8f10-21f6be1e81e2.png)

and if i fix the pivot table width, the problem now is when adding many columns  they disappears (not visible because of initial width fixed)

**Comment by jrowen** [comment]
I found wrapping the table in following helped:
```
<div style="overflow-x:auto">
...
</div>
```

**Comment by Seungwoo321** [comment]
This issue has been fixed
https://github.com/Seungwoo321/vue-pivottable/blob/master/src/Pivottable.js#L23
